dist: trusty
sudo: required
language: node_js
node_js:
  - "6"
cache:
  directories:
    - node_modules
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
env:
  matrix:
    - EMBER_TRY_SCENARIO=ember-release
    - EMBER_TRY_SCENARIO=ember-beta
    - EMBER_TRY_SCENARIO=ember-canary
  global:
    - secure: "oJiZIK+ngn8EdPFyf/b9vMC88SU+Elsm5gNEIN9Z/KGEh0adJQdgrY2a147pdUsfl5OEjo0WMtvV5gXJt3FGplGZIz6wRFdUbrYiAzSs47WjuWuyKX+N227/ssAr6JJCbuFjNIzYOjMALjjzT5zsFan9KlNgp5HidO5tZPhf+cgNlsZnd9AzcJ2dKm6UL8Bp+bNdnFnLaVZBsOBAupsptIF7fHaVVkTsaXNuJ1SA3r63Tunq2SAOanwn+0h08JB3ugGJ+a5KsZcDngGzBTett7Elmxs7FZFp4s1DTdgNFLMdnIZIsjCxj7TR/mFl0rg+pgcR+q4EObLH+1ynxgUsaZOnf7VoVTyJW9ns7l6+8B+LakJvOlgtdv2ozmmx+wQTKyBN7zcQS2M9Khbhly4D/Ur7ImXa4gNVInskheZvhoFeHK4h7HbDRPW8+N+0J3LDCZog9C2pVliVujW/HH6TQZFiVJr6FSbo2Raw/9oYR9RYsn5Q5DFkgb630STWSSpu7bZLNhjyy0pRAYRVpfyw9gjPqdCzjiAHcNpMjBfcjLdId51pZGBv7qbEZ3cgFvgfbq68Pi8FnXci+M44Dfcpui6zRApmR26dn+GXFuz8XvKB2rdtwoQDgfAbDvABJ4jY7YhLXMr925YwaQ3b6HyS11ywhXVMlsXrtdot/7P/N2o="

matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary

before_install:
  - "npm config set spin false"
  - "npm install -g npm@^2"

install:
  - npm install -g bower
  - npm install
  - bower install

script:
  - npm test
  - ember try $EMBER_TRY_SCENARIO test

after_script:
  - npm run build
  - ".travis/publish-gh-pages.sh"

after_success:
  - npm run coverage
  - npm run coveralls
